# Generated by Django 2.2.10 on 2021-07-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiPolls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.IntegerField(null=True, verbose_name='id пользователя'),
        ),
    ]
